config/routes.rb
TestProject::Application.routes.draw do
  get "home/index"
   post "home/index"

   root 'home#index'
  get "home/show"
   post "home/show"
   get "home/search"
   post "home/search"

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	require 'factual'
  def index  
        if params[:data]=="search" 
	  	factual = Factual.new("ZbZWd35dWdnpdtjvEYUXu820J0iivEwpEIU7wHDI", "CfAFBOAbM1s9hhVxhLR1brSnmNoOmYQOP9Aio5Ak")
	  	@factual=factual.table("places").select().filters({"locality" => params[:search]})
	  	#@factual=factual.table("places").select(:name, :website,:category_labels,:address).filters({"country" => "TH"})
    end
  end
  def show  	
  	
  end

  def search 	
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= link_to "Search by city From Factual.com",home_search_path%>
<br/><br/>
<%if !@factual.blank? %>
<h3>Record Found <%=@factual.count %></h3>
<table border="3">
	  <tr>
  	<th>Name</th>
    <th>Region</th>
    <th>Telephone</th>
    <th>Website</th>   
    <th>Country</th>
    <th>locality</th>
  </tr> 

<% @factual.each do |factual|%>
  <tr>
  	<td><%=factual['name']%></td>
    <td><%= factual['region']%></td>
    <td><%=factual['tel']%></td>
    <td><%=factual['website']%></td>
    <td><%=factual['country']%></td>
    <td><%=factual['locality']%></td>    
  </tr>
  <%end%> 
</table> 
 <%end%>

 

app/views/home/search.html.erb
<div >
<%= form_tag ('/home/index'),:method=>'post' do  %>
  
  <div class="field">
    <%= label_tag :search,"Please enter city name" %><br>
    <%= text_field_tag :search ,nil,:placeholder=>"Name"%>
     <%= hidden_field_tag :data ,nil,:value=>"search"%>
  </div>  
  <div class="actions">
    <%= submit_tag "Submit" %>
  </div>
<% end %>
</div>

app/views/home/show.html.erb
 <%if !@factual.blank?%>
<table border="3">
	  <tr>
  	<th>Name</th>
    <th>Region</th>
    <th>Telephone</th>
    <th>Website</th>
    <th>Telephone</th>
    <th>Country</th>
    <th>locality</th>
    <th>Address</th>

  </tr>
 
<% @factual.each do |factual|%>

  <tr>
  	<td><%=factual['name']%></td>
    <td><%= factual['region']%></td>
    <td><%=factual['tel']%></td>
    <td><%=factual['website']%></td>
    <td><%=factual['country']%></td>
    <td><%=factual['locality']%></td>
    <td><%=factual['address']%></td>
  </tr>
  <%end%>
  <%end%>
</table> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestProject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>